### ISSUE TITLE
bank transfer

### ISSUE THREAD

**Issue by bl0ody41** [qbcore-framework/qb-banking#102]
i cant transfer a money in the bank its showing like this 
![151191738-74a749af-9318-4227-ab5f-85c130e87aa2](https://github.com/qbcore-framework/qb-banking/assets/132123326/91c59a1e-266a-4cfc-99d2-99a00a71d471)

**Comment by Mil-Scripts** [comment]
any changes?

**Comment by Mil-Scripts** [comment]
> 

it seems like yes

**Comment by bl0ody41** [comment]
> bu hâlâ bir sorun mu?

yes bro this is problem for me
