### ISSUE TITLE
[BUG]atms not working

### ISSUE THREAD

**Issue by rezinator2-0** [qbcore-framework/qb-banking#122]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to '.atms..'
2. Click on 'nothing to interact with'
3. Use this item none' (item's name from shared.lua if applicable)
4. See error no error

**Expected behavior**
i have downloaded your new qb-banking i cant get any of the atms to work at all nothing shows up when i use qb-target and no e prompt shows up i have went into the bank and created a new card but i never get a card as an item if thats hpw its supposed to work or not

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: the most current
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by GhzGarage** [comment]
You order a bank card then use the bank card in front of the ATM

**Comment by CappyTech** [comment]
Maybe add a notification if at atm, and no card?
