### ISSUE TITLE
The line "provides qb-management" in the fxmanifest 

### ISSUE THREAD

**Issue by xCloudJumper420x** [qbcore-framework/qb-banking#124]
The line "provides qb-management" in the qb-banking fxmanifest causes qb-management to not start at all. Which in turn makes boss menus not open without restarting qb-management manually. I commented the line out of the fxmanifest and my management works like before. Just wanted to throw this out there.

**Comment by GhzGarage** [comment]
Thank you, i missed that on a PR that was submitted. I've removed it
