### ISSUE TITLE
[BUG] ATMs not working on ox_inventory

### ISSUE THREAD

**Issue by soniXx123** [qbcore-framework/qb-banking#127]
**Describe the bug**
Try to use the atms but is not working on ox_inventory. I think the meta information are not in the card.

**To Reproduce**
Buy an bank card with ox_inventory running.

**Screenshots**
![image](https://github.com/qbcore-framework/qb-banking/assets/35350615/916c5deb-18cb-4e71-9083-5fefbb02a43b)

**Comment by IAmDanielPeter** [comment]
Respectfully I think the creator should be looking at these issue tickets everyday. I'm having the same issue. Did you ever discover a fix?

**Comment by cekdat1** [comment]
I found a fix, but its only a patch kinda fix, unfortunately it wont allow for you to open others accounts with their respective card. but only your own account. still looking into figuring out opening the respective card owners account instead.

**Comment by MrTeaRexx** [comment]
does anyone have a fix for this?
