### ISSUE TITLE
An error happens for query "INSERT INTO bank_accounts

### ISSUE THREAD

**Issue by TTVPurpleUnicorn** [qbcore-framework/qb-banking#13]
![image](https://user-images.githubusercontent.com/89791405/131355845-6d48b109-1ebf-4796-8ddd-2c8b61e7af35.png)

error when adding a Saving account in bank, will still deposit cash or bank funds, , but table doesnt exsist.
so you just lose money without being able to withdrawl anything.

**Comment by TTVPurpleUnicorn** [comment]
![image](https://user-images.githubusercontent.com/89791405/131356679-f25ce549-ab25-49c0-b5ef-20d509da6768.png)

deposit error

**Comment by ItsAegeus** [comment]
Same for me can conform on updated and clean build.

**Comment by ihyajb** [comment]
This should have been fixed with the most recent updates to the TXAdmin build and qb-banking. Does this still occur?

**Comment by TTVPurpleUnicorn** [comment]
Yes, working wonderfully!
