### ISSUE TITLE
[BUG] Creating shared accounts doesn't have lower/upper case sensitive.

### ISSUE THREAD

**Issue by Nikwitz** [qbcore-framework/qb-banking#131]
**Describe the bug**
If you create a shared account called 'Shared' and someone afterwards create an account called 'shared' it will be visible in the banking list until you restart your game. The money is taken from your account and you can see them in the account, but it wont be visible after relog / server restart because it doesn't create it in the database. 

**To Reproduce**
1. Create an account named 'Shared' and it will be visible and inserted into the database correctly.
2. Create an account named 'shared' and it will be visible and not inserted into the database because the name has to be unique.

**Expected behavior**
The expected behavior would be that you get an error message that the name is already taken.

**Questions (please complete the following information):**
- When you last updated: today
- Are you using custom resource?: I'm using ox_lib, ox_inventory, ox_target, ox_fuel
 - Have you renamed `qb-` to something custom?: no

**Comment by ROLLINDOSES** [comment]
do you by chance know what the item is called

**Comment by Nikwitz** [comment]
> do you by chance know what the item is called

Which item?
