### ISSUE TITLE
[BUG] Unknown column 'account_name' in 'field list'

### ISSUE THREAD

**Issue by SmittySG** [qbcore-framework/qb-banking#132]
[script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @qb-banking/server.lua:89: qb-banking was unable to execute a query!
[script:qb-core] Query: INSERT INTO bank_statements (citizenid, account_name, amount, reason, statement_type) VALUES (?, ?, ?, ?, ?)
[script:qb-core] ["KLJ82723","checking",70000,"n","deposit"]
[script:qb-core] Unknown column 'account_name' in 'field list'

**Comment by Cocodrulo** [comment]
Have you executed the [SQL](https://github.com/qbcore-framework/qb-banking/blob/main/banking.sql) file? Because that column name seems to exists.
