### ISSUE TITLE
no /atm

### ISSUE THREAD

**Issue by PhantomPeppers** [qbcore-framework/qb-banking#16]
/atm isnt popping up as a command

**Comment by Developer-Bear** [comment]
Using latest version, command working as intended. https://gyazo.com/f23c35c78d658ddbcc200eeb8de9d7bf

**Comment by PhantomPeppers** [comment]
@Developer-Bear i updated just now there is no command its blank and doesnt do anything i can get the card and everything, is the command registered in a different script?

**Comment by PhantomPeppers** [comment]
ok so i seen theres qb atms i downloaded it got the command functioning but now im getting [      script:qb-atms] SCRIPT ERROR: @qb-atms/server/main.lua:56: attempt to call a nil value (field 'GetItemsByName') but i have visa and mastercard as items in my shared lua in my core

**Comment by PhantomPeppers** [comment]
i fixed it, i was missing the function in my core sorry for the confusion

**Comment by certifiedvenom** [comment]
what function was you missing because none of my atms are working
