### ISSUE TITLE
Oxmysql deprecation warning

### ISSUE THREAD

**Issue by mschiegg** [qbcore-framework/qb-banking#37]
Deprecation warning in Console if you update to Oxmysql >= 1.9

`[script:oxmysql] [WARNING] qb-banking triggered a deprecated function! Exports from prior to v1.9.0 will be removed in a future update.`      
`[script:oxmysql]       Refer to the readme for information on updating.`

**Comment by GhzGarage** [comment]
Update pushed, no more warning
