### ISSUE TITLE
[BUG] Bank transfers do not work

### ISSUE THREAD

**Issue by catiagomes94a** [qbcore-framework/qb-banking#40]
I wanted help to understand why bank transfers do not work, it always says that the number placed is not the right one.

![image](https://user-images.githubusercontent.com/72714315/151191738-74a749af-9318-4227-ab5f-85c130e87aa2.png)

**Comment by catiagomes94a** [comment]
> I wanted help to understand why bank transfers do not work, it always says that the number placed is not the right one.
> 
> ![image](https://user-images.githubusercontent.com/72714315/151191738-74a749af-9318-4227-ab5f-85c130e87aa2.png)

**Comment by EmreGumushan** [comment]
@catiagomes94a is this fixed ?

**Comment by catiagomes94a** [comment]
Hello,I still haven't had any response on this matter.

**Comment by Tttony2x** [comment]
I am also experiencing this issue.

**Comment by next-game** [comment]
it's strange that transfers work through the phone but they don't work through the bank

**Comment by catiagomes94a** [comment]
yes and even more no one answers on this subject.

**Comment by GhzGarage** [comment]
If you look at the code the entire transfer system is completely commented out. That's why it doesn't work
