### ISSUE TITLE
Qb banking glitch

### ISSUE THREAD

**Issue by GORPOwner** [qbcore-framework/qb-banking#45]
Hey so is the Qb banking broken? because someone just foound a flaw that if they transfer someone billions of dollars they go negative but the other person get billions in his bank. How can i fix this? ik this isnt a suppport channel but i just wanted to let this be known so it can be fixed

**Comment by milotiro95** [comment]
More info ? I just try and personally I don't have this bug ! I try with ATM, Phone & Bank transfer

**Comment by GORPOwner** [comment]
My players are able to send money and let there banks go negative and the other player recieves all that money.

**Comment by GORPOwner** [comment]
i also use another phone with a App called Wenmo

**Comment by milotiro95** [comment]
Then it's coming for you're phone not from qbcore because qb-phone doesn't have this bug.

**Comment by GORPOwner** [comment]
okok so time to dump the phone

**Comment by Branqueador** [comment]
> Then it's coming for you're phone not from qbcore because qb-phone doesn't have this bug.

yes you do have
