### ISSUE TITLE
[Suggestion] Adding savings account"!

### ISSUE THREAD

**Issue by Godzy69** [qbcore-framework/qb-banking#46]
As there is Savings Account, Could we make something that gives people "interest" on the money they keep in their saving account?

**Comment by restray** [comment]
Can you rename you issue please? With something like "[Suggestion] Adding savings account"!
That would help the QBCore team a lot 👍🏻 

(And +1 for this, even if it's hard to make configurable such a thing!)

**Comment by PlanovskyJus** [comment]
> As there is Savings Account, Could we make something that gives people "interest" on the money they keep in their saving account?

Done: https://github.com/qbcore-framework/qb-banking/pull/60
