### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TehGuardian** [qbcore-framework/qb-banking#67]
**Describe the bug**
Why is this in config if it doesn't do anything?

 Config.ATMModels = {
    "prop_atm_01",
    "prop_atm_02",
    "prop_atm_03",
    "prop_fleeca_atm"
}

**Comment by Flying-Turtles2** [comment]
That is how the script knows what an ATM is in game so that you can walk up to them and use /ATM when you have your debit card from the bank.

**Comment by GhzGarage** [comment]
This will be used when atms get merged into banking
