### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by AlbatracZ** [qbcore-framework/qb-banking#71]
**Is your feature request related to a problem? Please describe.**
i seeing this feature, but not showing on in-game bank

![deneme](https://user-images.githubusercontent.com/20631193/180671332-b9913846-044d-4bf9-8686-5c2183cfe701.png)

![image](https://user-images.githubusercontent.com/20631193/180671346-415e1e06-61b4-460e-bc86-4b3c2994db54.png)

**Comment by AlbatracZ** [comment]
i have already a debit card

**Comment by Getpwnedbydolbajoba** [comment]
@AlbatracZ at the moment that's not finished. Soon it will work.
