### ISSUE TITLE
[BUG] Banking System doesn't work for me

### ISSUE THREAD

**Issue by m0nst3rxd** [qbcore-framework/qb-banking#76]
Whenever I try to open the bank menu, nothing happens and I get an error in my console.
![Capture](https://user-images.githubusercontent.com/108489943/184505411-d07f3a21-c985-4c63-9288-714041e8782f.PNG)

**Comment by LV-Soft** [comment]
Since the last update, this resource needs a new table, but when a new installation is done, they forgot to create it in the database.

create the following table in MySQL:
```
CREATE TABLE IF NOT EXISTS `bank_cards` (
  `record_id` bigint(255) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50),
  `cardNumber` varchar(50) DEFAULT NULL,
  `cardPin` varchar(50) DEFAULT NULL,
  `cardActive` tinyint(4) DEFAULT 1,
  `cardLocked` tinyint(4) DEFAULT 0,
  `cardType` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`citizenid`),
  KEY `record_id` (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
```

**Comment by m0nst3rxd** [comment]
Thanks!
