### ISSUE TITLE
Banking Does Not Work[BUG]

### ISSUE THREAD

**Issue by PlzAdoptMee** [qbcore-framework/qb-banking#77]
When I try to goto the bank and press "E" nothing happens. When I check the live console and error shows up (posted below). How do I fix this?

[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @qb-banking/server/main.lua:215: qb-banking was unable to execute a query!
[      script:qb-core] Table 'zap894799-1.bank_cards' doesn't exist
[      script:qb-core] SELECT * FROM bank_cards WHERE citizenid = ? ORDER BY record_id DESC LIMIT 1 ["UXL45698"]

**Comment by LV-Soft** [comment]
new table is missing, create https://github.com/qbcore-framework/qb-banking/issues/79#issuecomment-1217250652
