### ISSUE TITLE
[BUG] Please Fix This Bug Urgent, When i Pressed "E" in Bank nothing happened!! 

### ISSUE THREAD

**Issue by power1s0n** [qbcore-framework/qb-banking#79]
writings in console
![Untitled](https://user-images.githubusercontent.com/111353739/184863109-8d81dae7-084d-43e0-9e84-552dc739d9cc.png)

**Comment by LV-Soft** [comment]
Since the last update, this resource needs a new table, but when a new installation is done, they forgot to create it in the database.

create the following table in MySQL:
```
CREATE TABLE IF NOT EXISTS `bank_cards` (
  `record_id` bigint(255) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50),
  `cardNumber` varchar(50) DEFAULT NULL,
  `cardPin` varchar(50) DEFAULT NULL,
  `cardActive` tinyint(4) DEFAULT 1,
  `cardLocked` tinyint(4) DEFAULT 0,
  `cardType` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`citizenid`),
  KEY `record_id` (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
```

**Comment by varch1tect** [comment]
@LV-Soft do you know if there is a difference between doing this on a windows install or a linux install?

The first time I did this I ran the SQL script in the repo through on a local windows install using phpmyadmin and it worked after restarging. But then I ran the script on a vps through a DB client, and I'm still getting the same "Table doesn't exist" error. I can confirm the DB has the bank_cards table.

The thing I can't wrap my head around is that my error is: Table 'QBCoreFramework_FC1BFD.bank_cards' doesn't exist, however my database is called qbcoreframework_fa0e9e.. The directly on the server is in fact server/txData/QBCoreFramework_FC1BFD.base, which has the same hash/id or whatever, but why is the database id/hash that was generated by txAdmin different? does the server have an abstracted database?

**Comment by Irishstevie** [comment]
This issue has been fixed <3
