### ISSUE TITLE
[BUG] Continuing issue wit multcharacter bank balance 

### ISSUE THREAD

**Issue by FrequencyRoleplay** [qbcore-framework/qb-banking#85]
I have had this issue for some time , even updated to most recent release and still have problem. 
The issue happens sometimes.  If you have mutilple characters , (qb-multicharcter) The bank balances will overwrite each other and all of charcters will have the same bank amounts.  Ive have numerous reports of it happeing with the latest being today.  Person have 3 characters , one had 1.2 million , not all 3 of theyre charcters have 119k. 

If the fix to not use multicharacter?  Is there a work around to prevent this?

**Comment by bluelineparabellum** [comment]
My community members characters will lost a huge amount of money from their bank accounts out of nowhere... not sure if this is the cause.

**Comment by sinphoenix** [comment]
Are you using any third party scripts for MultiCharacter, SpawnSelector, banking?
