### ISSUE TITLE
[BUG] pressing E to access bank and its not loading

### ISSUE THREAD

**Issue by h4n1793** [qbcore-framework/qb-banking#88]
**Describe the bug**
when entering the bank notification comes up to press E and nothing happens i have redownloaded the zip file and reinstalled it and its still not working, iv also added the new table on sql and still not working.

Error code
https://user-images.githubusercontent.com/121590734/209896062-403b0476-3c97-451d-b97d-3a8946ea0d96.png

**Comment by charj** [comment]
Database issue.
I'd reccomend recreating a brand new server with TXAdmin

The table might be there but the user fivem is connected with may not have permissions to use it.

**Comment by h4n1793** [comment]
it's with zap-hosting i created a new server when i encountered the problem
but was still there.

Thank you for the reply.

**Comment by charj** [comment]
I suspect this is an issue with Zap hosting specifically.
I created a brand new server only yesterday with TXAdmin and the db was created as expected

**Comment by Convictedgam3r** [comment]
has anyone figured out the reason behind zap-hosting bank for qb-core not working? i’ve entered the sql. did a complete copy paste from here add the ensure to the file for the banking and still not working
