### ISSUE TITLE
Savings log

### ISSUE THREAD

**Issue by SKITTLE6969** [qbcore-framework/qb-banking#97]
I don't know why but these two lines prevent saving from being logged, commenting these 2 out does.

https://github.com/qbcore-framework/qb-banking/blob/9b437d62ea3e2ea5583bd19a929207826a85107e/server/main.lua#L373

https://github.com/qbcore-framework/qb-banking/blob/9b437d62ea3e2ea5583bd19a929207826a85107e/server/main.lua#L390

**Comment by sinphoenix** [comment]
what log script are you using?

**Comment by SKITTLE6969** [comment]
@sinphoenix kak fixed it 
[#eb9e0b1](https://github.com/qbcore-framework/qb-banking/commit/eb9e0b1a4d1f038fe9bfb49b7c79605fe5db1ecc)
